spring.application.name=ms-relatorio
server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/db_relatorios
spring.ai.openai.api-key=${OPENAI_API_KEY}

core.ms1.url=http://localhost:8080
anamnese.ms2.url=http://localhost:8081