spring.application.name=ms-relatorio
server.port=8082

# Conexao direta para uso no IntelliJ
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/db_relatorios

spring.ai.openai.api-key=${OPENAI_API_KEY}

core.url=http://localhost:8080
anamnese.url=http://localhost:8081
